[project]
name = "labyrinthe-v1"
version = "0.1.0"
description = "Projet de labyrinthe avec pygame pour débutants"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "isort>=6.0.1",
    "pygame>=2.6.1",
    "pylint>=3.3.8",
]
